declare const _default: {
    Guilds: number;
    GuildMembers: number;
    GuildModeration: number;
    GuildEmojisAndStickers: number;
    GuildIntegrations: number;
    GuildWebhooks: number;
    GuildInvites: number;
    GuildVoiceStates: number;
    GuildPresences: number;
    GuildMessages: number;
    GuildMessageReactions: number;
    GuildMessageTyping: number;
    DirectMessages: number;
    DirectMessageReactions: number;
    DirectMessageTyping: number;
    MessageContent: number;
    GuildScheduledEvents: number;
    AutoModerationConfiguration: number;
    AutoModerationExecution: number;
};
export default _default;
